; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform  = espressif32@6.9.0
board     = esp32dev
board_build.partitions = partitions_singleapp_large.csv
upload_speed = 115200
monitor_speed = 115200
framework = espidf
lib_deps  =
    https://github.com/pschatzmann/ESP32-A2DP
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
build_flags =
    -DESP32=1
    -DESP32_CMAKE=1
    -DCONFIG_IDF_TARGET_ESP32=1
    -DA2DP_I2S_AUDIOTOOLS=1
    -DA2DP_LEGACY_I2S_SUPPORT=0
    -DA2DP_SPP_SUPPORT=0
    -Iinclude
    -Iassets
